# Generated by Django 5.2 on 2025-09-24 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_name', models.CharField(blank=True, max_length=100, null=True)),
                ('admin_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('admin_password', models.CharField(blank=True, max_length=200, null=True)),
                ('admin_role', models.CharField(default='admin', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('customer_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('customer_age', models.IntegerField(blank=True, null=True)),
                ('customer_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('customer_password', models.CharField(blank=True, max_length=200, null=True)),
                ('customer_role', models.CharField(default='customer', max_length=20)),
                ('customer_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('no choice', 'no choice')], default='no choice', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapist_name', models.CharField(max_length=100)),
                ('therapist_email', models.EmailField(blank=True, max_length=100, null=True)),
                ('therapist_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('year_of_experience', models.IntegerField(blank=True, null=True)),
                ('therapist_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('therapist_specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('therapist_qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('therapist_status', models.CharField(blank=True, max_length=100, null=True)),
                ('therapist_licence_number', models.IntegerField(blank=True, null=True)),
                ('therapist_Serve_for', models.CharField(blank=True, max_length=100, null=True)),
                ('therapist_password', models.CharField(blank=True, max_length=200, null=True)),
                ('therapist_role', models.CharField(blank=True, default='therapist', max_length=20, null=True)),
                ('therapist_gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('no choice', 'no choice')], default='no choice', max_length=150)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital_address', models.CharField(blank=True, max_length=300, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_rating', models.IntegerField(blank=True, null=True)),
                ('review_date', models.DateTimeField(auto_now=True, null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.customer')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.therapist')),
            ],
        ),
        migrations.CreateModel(
            name='UserAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.BigIntegerField()),
                ('user_name', models.CharField(blank=True, max_length=100, null=True)),
                ('user_password', models.CharField(blank=True, max_length=200, null=True)),
                ('user_role', models.CharField(blank=True, max_length=20, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
