# Generated by Django 5.2 on 2025-09-24 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_gender',
            field=models.CharField(blank=True, choices=[('male', 'male'), ('female', 'female'), ('no choice', 'no choice')], default='no choice', max_length=150, null=True),
        ),
    ]
