# Generated by Django 5.2 on 2025-10-02 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userauth_user_email_alter_admin_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='admin',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='therapist',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='admin',
            name='admin_email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='therapist_email',
            field=models.EmailField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='userauth',
            unique_together={('user_email', 'user_role')},
        ),
    ]
