# Generated by Django 5.2 on 2025-10-03 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_admin_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TherapistRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('year_of_experience', models.IntegerField(blank=True, null=True)),
                ('specialization', models.CharField(blank=True, max_length=100, null=True)),
                ('qualification', models.CharField(blank=True, max_length=200, null=True)),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('no choice', 'no choice')], default='no choice', max_length=150)),
                ('hospital_name', models.CharField(blank=True, max_length=200, null=True)),
                ('hospital_address', models.CharField(blank=True, max_length=300, null=True)),
                ('password', models.CharField(blank=True, max_length=200, null=True)),
                ('licence_pdf', models.FileField(blank=True, null=True, upload_to='pdf/request/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('declined', 'Declined')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='therapist_licence_number',
        ),
        migrations.AddField(
            model_name='therapist',
            name='therapist_licence',
            field=models.FileField(blank=True, null=True, upload_to='pdf/therapist_license/'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='customer_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='therapist_image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
