# Generated by Django 5.2 on 2025-10-10 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_therapistrequest_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapistrequest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
