# Generated by Django 5.2 on 2025-10-14 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_therapistrequest_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='hospital_address',
        ),
        migrations.RemoveField(
            model_name='therapist',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='therapistrequest',
            name='hospital_address',
        ),
        migrations.RemoveField(
            model_name='therapistrequest',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='therapist',
            name='hospital',
            field=models.ManyToManyField(blank=True, related_name='therapist', to='account.hospital'),
        ),
        migrations.AddField(
            model_name='therapistrequest',
            name='hospital',
            field=models.ManyToManyField(blank=True, related_name='therapist_requests', to='account.hospital'),
        ),
    ]
