# Generated by Django 5.2 on 2025-09-24 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(blank=True, max_length=200, null=True)),
                ('blog_content', models.TextField(blank=True, null=True)),
                ('blog_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('blog_created_at', models.DateTimeField(auto_now_add=True)),
                ('blog_updated_at', models.DateTimeField(auto_now=True)),
                ('blog_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.userauth')),
            ],
        ),
    ]
