# Generated by Django 5.2 on 2025-10-06 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_author_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
