# Generated by Django 5.2 on 2025-10-08 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_therapistrequest_and_more'),
        ('blog', '0002_blog_blog_author_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.userauth'),
        ),
    ]
