# Generated by Django 5.2 on 2025-10-14 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_hospital_remove_therapist_hospital_address_and_more'),
        ('therapy', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='hospital_address',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='hospital_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='account.hospital'),
        ),
    ]
